export { About } from './About/About'
export { ContactUs } from './ContactUs/Contactus'
export { Gallery } from './Gallery/Gallery'
export { Home } from './Home/Home'
export { Login } from './Login/Login'
export { Register } from './Register/Register'
export { WelcomePage } from './WelcomePage/WelcomePage'
